// src/components/OverviewDashboard.vue
<script setup lang="ts">
import { computed } from "vue";
import type { OverviewResult } from "../services/api";
import type { ObservationRecord } from "../../shared/observation";

const props = defineProps<{ overview: OverviewResult | null; observations: ObservationRecord[] }>();

const MODALITY_LABELS: Record<string, string> = {
  resonador: "Resonadores",
  tomografo: "Tomógrafos",
  ecografo: "Ecógrafos",
  "rayos-x": "Rayos X",
  mamografo: "Mamógrafos",
  otra: "Otros",
};

function maxOf(entries: [string, number][]): number {
  return Math.max(1, ...entries.map(([, n]) => n));
}

const geoTree = computed(() => {
  const tree = new Map<string, Map<string, Map<string, number>>>();
  for (const o of props.observations) {
    const country = o.country ?? "Sin país";
    const city = o.city ?? "Sin ciudad";
    const client = o.client ?? "Sin cliente";
    const cities = tree.get(country) ?? new Map();
    const clients = cities.get(city) ?? new Map();
    clients.set(client, (clients.get(client) ?? 0) + 1);
    cities.set(city, clients);
    tree.set(country, cities);
  }
  return [...tree.entries()].map(([country, cities]) => ({
    country,
    cities: [...cities.entries()].map(([city, clients]) => ({
      city,
      clients: [...clients.entries()].map(([client, n]) => ({ client, n })),
    })),
  }));
});
</script>

<template>
  <section class="card">
    <h2>Resumen global</h2>
    <div v-if="!overview" class="muted">Cargando…</div>
    <div v-else>
      <p class="stat">{{ overview.observations }} observaciones · {{ overview.fieldsUnknown }} campos por verificar</p>
      <h3>Por modalidad</h3>
      <div v-for="([k, n]) in Object.entries(overview.byModality)" :key="k" class="bar-row">
        <span>{{ MODALITY_LABELS[k] ?? k }}</span>
        <div class="bar"><div :style="{ width: `${(n / maxOf(Object.entries(overview.byModality))) * 100}%` }" /></div>
        <b>{{ n }}</b>
      </div>
      <h3>Mapa geográfico</h3>
      <details v-for="g in geoTree" :key="g.country" class="geo-node">
        <summary>{{ g.country }} ({{ g.cities.reduce((a, c) => a + c.clients.reduce((b, cl) => b + cl.n, 0), 0) }} obs.)</summary>
        <details v-for="c in g.cities" :key="c.city" class="geo-node" style="margin-left: 1rem">
          <summary>{{ c.city }} ({{ c.clients.reduce((a, cl) => a + cl.n, 0) }})</summary>
          <ul style="margin-left: 2rem">
            <li v-for="cl in c.clients" :key="cl.client">{{ cl.client }} ({{ cl.n }})</li>
          </ul>
        </details>
      </details>
      <p v-if="geoTree.length === 0" class="muted">Sin datos geográficos.</p>
      <h3>Oportunidades de renovación <small>(≥ 7 años)</small></h3>
      <ul v-if="overview.renewals.length > 0" class="renew">
        <li v-for="(r, i) in overview.renewals" :key="i">
          {{ r.client }} · {{ r.modality ?? "equipo" }}{{ r.brand ? ` ${r.brand}` : "" }}{{ r.model ? ` ${r.model}` : "" }} · {{ r.ageYears }} años
        </li>
      </ul>
      <p v-else class="muted">Sin equipos en edad de renovación.</p>
      <h3>Frescura de datos</h3>
      <p v-if="overview.stale.length === 0" class="muted">Todo verificado recientemente.</p>
      <p v-for="(s, i) in overview.stale" :key="i" class="question">{{ s }}</p>
      <h3>Conflictos <small>(no se fusionan solos)</small></h3>
      <p v-if="overview.conflicts.length === 0" class="muted">Sin observaciones contradictorias.</p>
      <p v-for="(c, i) in overview.conflicts" :key="i" class="question">
        {{ c.client }} · {{ c.modality }}: {{ c.detail }} ({{ c.dates.join(" / ") }})
      </p>
      <p v-for="(d, i) in overview.duplicates" :key="i" class="question">Posible duplicado: {{ d }}</p>
    </div>
  </section>
</template>

// src/components/OverviewDashboard.tsx
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import type { ObservationRecord } from "../../shared/observation";
import type { OverviewResult } from "../lib/store";
import { useTheme, type Theme } from "../lib/theme";

const MODALITY_LABELS: Record<string, string> = {
  resonador: "Resonadores",
  tomografo: "Tomógrafos",
  ecografo: "Ecógrafos",
  "rayos-x": "Rayos X",
  mamografo: "Mamógrafos",
  otra: "Otros",
};

function maxOf(entries: [string, number][]): number {
  return Math.max(1, ...entries.map(([, n]) => n));
}

export function OverviewDashboard({ overview, observations }: { overview: OverviewResult | null; observations: ObservationRecord[] }) {
  const { theme } = useTheme();
  const styles = makeStyles(theme);
  if (!overview) return <View style={styles.card}><Text style={styles.h2}>Resumen</Text><Text style={styles.muted}>Cargando…</Text></View>;

  const geoTree = buildGeoTree(observations);
  const modEntries = Object.entries(overview.byModality);
  const max = maxOf(modEntries);

  return (
    <View style={styles.card}>
      <Text style={styles.h2}>Resumen</Text>
      <Text style={styles.stat}>{overview.observations} observaciones · {overview.fieldsUnknown} campos por verificar</Text>

      <Text style={styles.h3}>Por modalidad</Text>
      {modEntries.length === 0 ? <Text style={styles.muted}>Sin datos.</Text> : modEntries.map(([k, n]) => (
        <View key={k} style={styles.barRow}>
          <Text style={styles.barLabel} numberOfLines={1} ellipsizeMode="tail">{MODALITY_LABELS[k] ?? k}</Text>
          <View style={styles.barTrack}>
            <View style={[styles.barFill, { width: `${Math.min(100, (n / max) * 100)}%` }]} />
          </View>
          <Text style={styles.barNum} numberOfLines={1}>{n}</Text>
        </View>
      ))}

      <Text style={styles.h3}>Mapa geográfico</Text>
      {geoTree.length === 0 ? <Text style={styles.muted}>Sin datos geográficos.</Text> : (
        geoTree.map((g) => <CountryNode key={g.country} data={g} theme={theme} />)
      )}

      <Text style={styles.h3}>Oportunidades de renovación <Text style={styles.mutedSmall}>(≥ 7 años)</Text></Text>
      {overview.renewals.length === 0 ? <Text style={styles.muted}>Sin equipos en edad de renovación.</Text> : (
        overview.renewals.map((r, i) => (
          <Text key={i} style={styles.renewItem}>
            {r.client} · {r.modality ?? "equipo"}{r.brand ? ` ${r.brand}` : ""}{r.model ? ` ${r.model}` : ""} · {r.ageYears} años
          </Text>
        ))
      )}

      <Text style={styles.h3}>Frescura de datos</Text>
      {overview.stale.length === 0 ? <Text style={styles.muted}>Todo verificado recientemente.</Text> : (
        overview.stale.map((s, i) => <Text key={i} style={styles.question}>{s}</Text>)
      )}

      <Text style={styles.h3}>Conflictos <Text style={styles.mutedSmall}>(no se fusionan solos)</Text></Text>
      {overview.conflicts.length === 0 ? <Text style={styles.muted}>Sin observaciones contradictorias.</Text> : (
        overview.conflicts.map((c, i) => (
          <Text key={i} style={styles.question}>{c.client} · {c.modality}: {c.detail} ({c.dates.join(" / ")})</Text>
        ))
      )}
      {overview.duplicates.map((d, i) => <Text key={`d${i}`} style={styles.question}>Posible duplicado: {d}</Text>)}
    </View>
  );
}

interface GeoLeafData { city: string; client: string; n: number }
interface GeoNodeData { country: string; total: number; leaves: GeoLeafData[] }

function buildGeoTree(obs: ObservationRecord[]): GeoNodeData[] {
  const tree = new Map<string, Map<string, number>>();
  for (const o of obs) {
    const country = o.country ?? "Sin país";
    const city = o.city ?? "Sin ciudad";
    const client = o.client ?? "Sin cliente";
    const leaves = tree.get(country) ?? new Map();
    const key = `${city}||${client}`;
    leaves.set(key, (leaves.get(key) ?? 0) + 1);
    tree.set(country, leaves);
  }
  return [...tree.entries()].map(([country, leaves]) => {
    const leafRows = [...leaves.entries()].map(([key, n]) => {
      const [city, client] = key.split("||");
      return { city, client, n };
    });
    return { country, leaves: leafRows, total: leafRows.reduce((a, c) => a + c.n, 0) };
  });
}

// Un único nivel de despliegue (país → cliente): dos niveles anidados hacían
// que el primer toque pareciera no hacer nada al revelar solo un nodo intermedio.
function CountryNode({ data, theme }: { data: GeoNodeData; theme: Theme }) {
  const [expanded, setExpanded] = useState(false);
  const styles = makeStyles(theme);
  return (
    <View>
      <Pressable onPress={() => setExpanded((e) => !e)} style={styles.geoNodeRow} hitSlop={6}>
        <Text style={styles.geoChevron}>{expanded ? "▼" : "▶"}</Text>
        <Text style={styles.geoNode}>{data.country} ({data.total} obs.)</Text>
      </Pressable>
      {expanded && (
        data.leaves.length === 0 ? (
          <Text style={styles.geoEmpty}>Sin observaciones en este país.</Text>
        ) : (
          data.leaves.map((l) => (
            <Text key={`${l.city}||${l.client}`} style={styles.geoLeaf}>
              · {l.client}{l.city !== "Sin ciudad" ? ` — ${l.city}` : ""} ({l.n})
            </Text>
          ))
        )
      )}
    </View>
  );
}

function makeStyles(theme: Theme) {
  return StyleSheet.create({
    card: { backgroundColor: theme.surface, borderRadius: 12, padding: 16, gap: 10 },
    h2: { color: theme.text, fontSize: 18, fontWeight: "600" },
    h3: { color: theme.text, fontSize: 14, fontWeight: "600", marginTop: 4 },
    stat: { color: theme.textMuted, fontSize: 13 },
    muted: { color: theme.textMuted, fontSize: 12 },
    mutedSmall: { color: theme.textMuted, fontSize: 11, fontWeight: "400" },
    barRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    barLabel: { color: theme.textMuted, fontSize: 11, width: 88, flexShrink: 0 },
    barTrack: { flex: 1, height: 8, backgroundColor: theme.surfaceAlt, borderRadius: 4, overflow: "hidden" },
    barFill: { height: "100%", backgroundColor: theme.accent, borderRadius: 4 },
    barNum: { color: theme.text, fontSize: 12, fontWeight: "600", minWidth: 32, textAlign: "right", flexShrink: 0 },
    geoNodeRow: { flexDirection: "row", alignItems: "center", gap: 6, paddingVertical: 6 },
    geoChevron: { color: theme.accent, fontSize: 11, width: 12 },
    geoNode: { color: theme.text, fontSize: 13, fontWeight: "600", flexShrink: 1 },
    geoEmpty: { color: theme.textMuted, fontSize: 11, marginLeft: 18, paddingVertical: 2 },
    geoLeaf: { color: theme.textMuted, fontSize: 12, paddingVertical: 3, marginLeft: 18 },
    renewItem: { color: theme.textMuted, fontSize: 12, paddingVertical: 2 },
    question: { color: theme.warningText, fontSize: 12, paddingVertical: 2 },
  });
}
